src/Entity/Tasks.php
<?php

namespace App\Entity;

use App\Repository\TasksRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TasksRepository::class)
 */
class Tasks
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $timer;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_end;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_user;

    /**
     * @ORM\ManyToOne(targetEntity=Projects::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTimer(): ?int
    {
        return $this->timer;
    }

    public function setTimer(?int $timer): self
    {
        $this->timer = $timer;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdProject(): ?Projects
    {
        return $this->id_project;
    }

    public function setIdProject(?Projects $id_project): self
    {
        $this->id_project = $id_project;

        return $this;
    }
}

src/Form/TasksType.php
<?php

namespace App\Form;

use App\Entity\Projects;
use App\Entity\Tasks;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TasksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('id_user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
            ])
            ->add('id_project', EntityType::class, [
                'class' => Projects::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tasks::class,
        ]);
    }
}

src/Controller/TasksController.php
<?php

namespace App\Controller;

use App\Entity\Tasks;
use App\Form\TasksType;
use App\Repository\TasksRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tasks")
 */
class TasksController extends AbstractController
{

    /**
     * @Route("/new", name="tasks_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $task = new Tasks();
        $form = $this->createForm(TasksType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirect($this->generateUrl('project_show', ['id' => $task->getIdProject()->getId()]));
        }

        return $this->render('tasks/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="tasks_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tasks $task): Response
    {
        $form = $this->createForm(TasksType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirect($this->generateUrl('task_show', ['id' => $task->getId()]));
        }

        return $this->render('tasks/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="tasks_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tasks $task): Response
    {
        if ($this->isCsrfTokenValid('delete' . $task->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tasks');
    }

    /**
     * @Route("/show/{id}", name="task_show", methods={"GET","POST"})
     */
    public function showtask(TasksRepository $tasksRepository, Tasks $task): Response
    {
        $seconds = $task->getTimer();
        if (isset($seconds)) {
            $timer = gmdate("H:i:s", $seconds);
        } else {
            $seconds = 0;
            $timer = "";
        }

        return $this->render('tasks/task.html.twig', [
            'seconds' => $seconds,
            'timer' => $timer,
            'task' => $tasksRepository->findTask($task->getId()),
        ]);
    }

    /**
     * @Route("/ajax/task/start", name="ajax_task_start", methods={"GET","POST"})
     */
    public function startTimer(Request $request): Response
    {
        $taskId = $request->get('taskId');
        $task = $this->getDoctrine()->getRepository(Tasks::class)->find($taskId);
        $date = $task->getDateStart();

        $startDate = new \DateTime();
        $startDate->format('Y-m-d\TH:i:s.u');

        if (!isset($date)) {
            $task->setDateStart($startDate);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();
        }

        return $this->json("ok");
    }

    /**
     * @Route("/ajax/task/stop", name="ajax_task_stop", methods={"GET","POST"})
     */
    public function stopTimer(Request $request): Response
    {
        $taskId = $request->get('taskId');
        $task = $this->getDoctrine()->getRepository(Tasks::class)->find($taskId);

        $dateEnd = new \DateTime();
        $dateEnd->format('Y-m-d\TH:i:s.u');

        $time = $request->get('time');
        $str_time = preg_replace("/^([\d]{1,2})\:([\d]{2})$/", "00:$1:$2", $time);
        sscanf($str_time, "%d:%d:%d", $hours, $minutes, $seconds);
        $time_seconds = $hours * 3600 + $minutes * 60 + $seconds;

        $task->setTimer($time_seconds);
        $task->setDateEnd($dateEnd);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($task);
        $entityManager->flush();


        return $this->json("ok");
    }
}

templates/tasks/_delete_form.html.twig
<form method="post" action="{{ path('tasks_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tasks/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tasks/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tasks{% endblock %}

{% block body %}
    <h1>Edit Tasks</h1>

    {{ include('tasks/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('tasks/_delete_form.html.twig') }}
{% endblock %}

templates/tasks/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tasks index{% endblock %}

{% block body %}
    <h1>Tasks index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Timer</th>
                <th>Date_start</th>
                <th>Date_end</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.timer|date('H:i:s', '+00:00 GMT') }} </td>
                <td>{{ task.dateStart ? task.dateStart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ task.dateEnd ? task.dateEnd|date('Y-m-d H:i:s') : '' }}</td>
                <td><a href="{{ path('task_show', {'id': task.id}) }}">{{ task.name }}</a></td>
                <td>
                    <a class="btn" href="{{ path('tasks_edit', {'id': task.id}) }}">edit</a>
                    {{ include('tasks/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tasks_new') }}">Create new</a>
{% endblock %}

templates/tasks/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tasks{% endblock %}

{% block body %}
    <h1>Create new Tasks</h1>

    {{ include('tasks/_form.html.twig') }}
{% endblock %}

templates/tasks/task.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chrono Task{% endblock %}

{% block body %}
    <h1>{{ task.0.name }}</h1>

    <form name="chronoForm">
        <input type="text" name="chronotime" id="chronotime" value="0:00:00"/>
        <input type="button" name="startstop" value="start!" onClick="chronoStart()"/>
        <input type="button" name="reset" value="reset!" onClick="chronoReset()"/>
    </form>
{% endblock %}

{% block javascripts %}
    <script>
        var startTime = 0;
        var start = 0;
        var end = 0;
        var diff = 0;
        var timerID = 0;
        var timer = "{{ timer }}";
        var seconds = {{ seconds }};

        if (timer !== "") {
            document.getElementById("chronotime").value = timer;
        }

        function chrono() {
            end = new Date();
            diff = end - start;
            diff = new Date(diff);
            var sec = diff.getSeconds();
            var min = diff.getMinutes();
            var hr = diff.getHours() - 1;
            if (min < 10) {
                min = "0" + min
            }
            if (sec < 10) {
                sec = "0" + sec
            }
            document.getElementById("chronotime").value = hr + ":" + min + ":" + sec;
            timerID = setTimeout("chrono()", 10);
        }

        function chronoStart() {
            document.chronoForm.startstop.value = "stop!";
            document.chronoForm.startstop.onclick = chronoStop;
            document.chronoForm.reset.onclick = chronoReset;
            var taskId = {{ task.0.id }};
            $.ajax({
                url: "{{ path('ajax_task_start') }}",
                dataType: 'json',
                data: {taskId: taskId},
                type: "POST",
                success: function () {
                    start = new Date();
                    if (seconds !== null) {
                        start.setSeconds(start.getSeconds() - seconds);
                    }
                    chrono();
                }
            });
        }

        function chronoContinue() {
            document.chronoForm.startstop.value = "stop!";
            document.chronoForm.startstop.onclick = chronoStop;
            document.chronoForm.reset.onclick = chronoReset;
            start = new Date() - diff;
            start = new Date(start);
            chrono();
        }

        function chronoReset() {
            document.getElementById("chronotime").value = "0:00:00";
            start = new Date();
            seconds = 0;
        }

        function chronoStopReset() {
            document.getElementById("chronotime").value = "0:00:00";
            document.chronoForm.startstop.onclick = chronoStart;
        }

        function chronoStop() {
            document.chronoForm.startstop.value = "start!";
            document.chronoForm.startstop.onclick = chronoContinue;
            document.chronoForm.reset.onclick = chronoStopReset;
            clearTimeout(timerID);
            var time = document.getElementById("chronotime").value;
            var taskId = {{ task.0.id }};
            $.ajax({
                url: "{{ path('ajax_task_stop') }}",
                dataType: 'json',
                data: {taskId: taskId, time: time},
                type: "POST"
            });
        }
    </script>
{% endblock %}